Board Support Package: common/drivers/microsd.c File Reference
microsd.c File Reference
Micro SD card driver for the EFM32GG_DK3750 development kit.
#include "diskio.h"
#include "microsd.h"
#include "em_device.h"
#include "microsdconfig.h"
#include "em_gpio.h"
#include "integer.h"
#include "em_cmu.h"
#include "em_usart.h"
Functions
void MICROSD_init (void)
Initialize SPI setting.
void MICROSD_deinit (void)
Deinitialize SPI setting.
uint8_t xfer_spi (uint8_t data)
Do one SPI transfer on a SD-card.
static uint8_t wait_ready (void)
Wait for card ready.
void deselect (void)
Deselect the card and release SPI bus.
int select (void)
Select the card and wait ready.
void power_on (void)
Turn on SD card power DK doesn't support socket power control, only enable the SPI clock.
void power_off (void)
Turn off SD card power DK doesn't support socket power control, only disable the SPI clock.
int rcvr_datablock (uint8_t *buff, uint32_t btr)
Receive a data packet from MMC.
int xmit_datablock (const uint8_t *buff, uint8_t token)
Send a data packet to MMC.
uint8_t send_cmd (uint8_t cmd, DWORD arg)
Send a command packet to MMC.
Detailed Description
Micro SD card driver for the EFM32GG_DK3750 development kit.
This file provides the interface layer between the DK and the fat filesystem provided.
Author:
Energy Micro AS
Version:
1.0.0
(C) Copyright 2012 Energy Micro AS, http://www.energymicro.com
Permission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:
1. The origin of this software must not be misrepresented; you must not claim that you wrote the original software. 2. Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software. 3. This notice may not be removed or altered from any source distribution. 4. The source and compiled code may only be used on Energy Micro "EFM32" microcontrollers and "EFR4" radios.
DISCLAIMER OF WARRANTY/LIMITATION OF REMEDIES: Energy Micro AS has no obligation to support this Software. Energy Micro AS is providing the Software "AS IS", with no express or implied warranties of any kind, including, but not limited to, any implied warranties of merchantability or fitness for any particular purpose or warranties against infringement of any proprietary rights of a third party.
Energy Micro AS will not be liable for any consequential, incidental, or special damages, or any other relief, or for any claim by any third party, arising from your use of this Software.
Definition in file microsd.c.
Function Documentation
static uint8_t wait_ready (void) [static]
Wait for card ready.
Returns:
0xff: card ready, other value: card not ready
Definition at line 135 of file microsd.c.
References xfer_spi().
Referenced by select(), and xmit_datablock().