Board Support Package: MicroSd
MicroSd
[Drivers]
Defines
#define CMD0 (0)
GO_IDLE_STATE.
#define CMD1 (1)
SEND_OP_COND.
#define ACMD41 (41 | 0x80)
SEND_OP_COND (SDC).
#define CMD8 (8)
SEND_IF_COND.
#define CMD9 (9)
SEND_CSD.
#define CMD10 (10)
SEND_CID.
#define CMD12 (12)
STOP_TRANSMISSION.
#define ACMD13 (13 | 0x80)
SD_STATUS (SDC).
#define CMD16 (16)
SET_BLOCKLEN.
#define CMD17 (17)
READ_SINGLE_BLOCK.
#define CMD18 (18)
READ_MULTIPLE_BLOCK.
#define CMD23 (23)
SET_BLOCK_COUNT.
#define ACMD23 (23 | 0x80)
SET_WR_BLK_ERASE_COUNT (SDC).
#define CMD24 (24)
WRITE_BLOCK.
#define CMD25 (25)
WRITE_MULTIPLE_BLOCK.
#define CMD41 (41)
SEND_OP_COND (ACMD).
#define CMD55 (55)
APP_CMD.
#define CMD58 (58)
READ_OCR.
Functions
void MICROSD_init (void)
Initialize SPI setting.
void MICROSD_deinit (void)
Deinitialize SPI setting.
void deselect (void)
Deselect the card and release SPI bus.
void power_on (void)
Turn on SD card power DK doesn't support socket power control, only enable the SPI clock.
void power_off (void)
Turn off SD card power DK doesn't support socket power control, only disable the SPI clock.
int rcvr_datablock (uint8_t *buff, uint32_t btr)
Receive a data packet from MMC.
int select (void)
Select the card and wait ready.
uint8_t send_cmd (uint8_t cmd, DWORD arg)
Send a command packet to MMC.
uint8_t xfer_spi (uint8_t data)
Do one SPI transfer on a SD-card.
int xmit_datablock (const uint8_t *buff, uint8_t token)
Send a data packet to MMC.
Define Documentation
#define ACMD13 (13 | 0x80)
SD_STATUS (SDC).
Definition at line 71 of file microsd.h.
#define ACMD23 (23 | 0x80)
SET_WR_BLK_ERASE_COUNT (SDC).
Definition at line 76 of file microsd.h.
#define ACMD41 (41 | 0x80)
SEND_OP_COND (SDC).
Definition at line 66 of file microsd.h.
#define CMD0 (0)
GO_IDLE_STATE.
Definition at line 64 of file microsd.h.
Referenced by send_cmd().
#define CMD1 (1)
SEND_OP_COND.
Definition at line 65 of file microsd.h.
#define CMD10 (10)
SEND_CID.
Definition at line 69 of file microsd.h.
#define CMD12 (12)
STOP_TRANSMISSION.
Definition at line 70 of file microsd.h.
Referenced by send_cmd().
#define CMD16 (16)
SET_BLOCKLEN.
Definition at line 72 of file microsd.h.
#define CMD17 (17)
READ_SINGLE_BLOCK.
Definition at line 73 of file microsd.h.
#define CMD18 (18)
READ_MULTIPLE_BLOCK.
Definition at line 74 of file microsd.h.
#define CMD23 (23)
SET_BLOCK_COUNT.
Definition at line 75 of file microsd.h.
#define CMD24 (24)
WRITE_BLOCK.
Definition at line 77 of file microsd.h.
#define CMD25 (25)
WRITE_MULTIPLE_BLOCK.
Definition at line 78 of file microsd.h.
#define CMD41 (41)
SEND_OP_COND (ACMD).
Definition at line 79 of file microsd.h.
#define CMD55 (55)
APP_CMD.
Definition at line 80 of file microsd.h.
Referenced by send_cmd().
#define CMD58 (58)
READ_OCR.
Definition at line 81 of file microsd.h.
#define CMD8 (8)
SEND_IF_COND.
Definition at line 67 of file microsd.h.
Referenced by send_cmd().
#define CMD9 (9)
SEND_CSD.
Definition at line 68 of file microsd.h.
Function Documentation
void deselect (void)
Deselect the card and release SPI bus.
Definition at line 149 of file microsd.c.
References xfer_spi().
Referenced by power_off(), select(), and send_cmd().
void MICROSD_deinit (void)
Deinitialize SPI setting.
Releases any resources alliocated in the initialization.
Definition at line 100 of file microsd.c.
void MICROSD_init (void)
Initialize SPI setting.
The MicroSD card is connected to USART0, location #2. The FatFS system controls the SPI CS directly through the macros CS_HIGH() and CS_LOW().
Definition at line 59 of file microsd.c.
void power_off (void)
Turn off SD card power DK doesn't support socket power control, only disable the SPI clock.
Definition at line 184 of file microsd.c.
References deselect(), and select().
void power_on (void)
Turn on SD card power DK doesn't support socket power control, only enable the SPI clock.
Definition at line 174 of file microsd.c.
int rcvr_datablock (uint8_t * buff, uint32_t btr)
Receive a data packet from MMC.
Parameters:
[out] buff Data buffer to store received data
btr Byte count (must be multiple of 4)
Returns:
1:OK, 0:Failed
Definition at line 204 of file microsd.c.
References xfer_spi().
int select (void)
Select the card and wait ready.
Returns:
1:Successful, 0:Timeout
Definition at line 159 of file microsd.c.
References deselect(), and wait_ready().
Referenced by power_off(), and send_cmd().
uint8_t send_cmd (uint8_t cmd, DWORD arg)
Send a command packet to MMC.
Parameters:
[in] cmd Command byte
[in] arg Argument
Returns:
Response value
Definition at line 304 of file microsd.c.
References CMD0, CMD12, CMD55, CMD8, deselect(), select(), send_cmd(), and xfer_spi().
Referenced by send_cmd().
uint8_t xfer_spi (uint8_t data)
Do one SPI transfer on a SD-card.
Parameters:
data Byte to transmit
Returns:
Byte received
Definition at line 121 of file microsd.c.
Referenced by deselect(), rcvr_datablock(), send_cmd(), wait_ready(), and xmit_datablock().
int xmit_datablock (const uint8_t * buff, uint8_t token)
Send a data packet to MMC.
Parameters:
[in] buff 512 bytes data block to be transmitted
token Data token
Returns:
1:OK, 0:Failed
Definition at line 263 of file microsd.c.
References wait_ready(), and xfer_spi().