Board Support Package: RtcDrv
RtcDrv
[Drivers]
Functions
void RTCDRV_Delay (uint32_t msec, bool useEM2)
RTC delay function.
void RTCDRV_Trigger (uint32_t msec, void(*cb)(void))
RTC trigger enable.
void RTCDRV_Setup (CMU_Select_TypeDef lfaClockSrc, CMU_ClkDiv_TypeDef rtcPrescale)
Setup RTC with selected clock source and prescaler.
Function Documentation
void RTCDRV_Delay (uint32_t msec, bool useEM2)
RTC delay function.
Parameters:
msec Number of msec to delay
useEM2 Enter EM2 while waiting
Definition at line 103 of file rtcdrv.c.
References DelayCB(), rtcDelayComplete, and RTCDRV_Trigger().
void RTCDRV_Setup (CMU_Select_TypeDef lfaClockSrc, CMU_ClkDiv_TypeDef rtcPrescale)
Setup RTC with selected clock source and prescaler.
Parameters:
lfaClockSrc Clock source to use for LFA clock
rtcPrescale RTC prescaler
Definition at line 65 of file rtcdrv.c.
References rtcFreq, and rtcInitialized.
Referenced by RTCDRV_Trigger().
void RTCDRV_Trigger (uint32_t msec, void(*)(void) cb)
RTC trigger enable.
Parameters:
msec Enable trigger in msec
cb Callback invoked when msec elapsed
Definition at line 144 of file rtcdrv.c.
References rtcCb, RTCDRV_Setup(), rtcFreq, and rtcInitialized.
Referenced by RTCDRV_Delay().