Board Support Package: I2c
I2c
[Drivers]
Functions
void I2CDRV_Init (const I2C_Init_TypeDef *init)
Initalize basic I2C master mode driver for use on the DK.
I2C_TransferReturn_TypeDef I2CDRV_Transfer (I2C_TransferSeq_TypeDef *seq)
Perform I2C transfer.
Function Documentation
void I2CDRV_Init (const I2C_Init_TypeDef * init)
Initalize basic I2C master mode driver for use on the DK.
This driver only supports master mode, single bus-master. In addition to configuring the EFM32 I2C peripheral module, it also configures DK specific setup in order to use the I2C bus.
Parameters:
[in] init Pointer to I2C initialization structure.
Definition at line 58 of file i2cdrv.c.
References BSP_I2C, and BSP_PeripheralAccess().
I2C_TransferReturn_TypeDef I2CDRV_Transfer (I2C_TransferSeq_TypeDef * seq)
Perform I2C transfer.
This driver only supports master mode, single bus-master. It does not return until the transfer is complete, polling for completion.
Parameters:
[in] seq Pointer to sequence structure defining the I2C transfer to take place. The referenced structure must exist until the transfer has fully completed.
Definition at line 107 of file i2cdrv.c.
Referenced by EEPROM_AckPoll(), EEPROM_Read(), EEPROM_Write(), TEMPSENS_RegisterGet(), and TEMPSENS_RegisterSet().